Tutorial-Analysis:
  ref_path: $FINITEDEPTH_DATA/ref1.png
  coat_path: $FINITEDEPTH_DATA/coat1.png
  reference:
    templateROI: [200, 50, 1200, 200]
    substrateROI: [400, 175, 1000, 500]
  analysis:
    parameters:
      ref_visual: output/ref.jpg
      subst_visual: output/subst.jpg
      layer_visual: output/coat.jpg
