Analysis1:
  ref_path: $FINITEDEPTH_DATA/ref1.png
  coat_path: $FINITEDEPTH_DATA/coat1.png
  reference:
    templateROI: [200, 50, 1200, 200]
    substrateROI: [400, 175, 1000, 500]
  analysis:
    parameters:
      layer_visual: result1.jpg
