Analysis-Circ:
  ref_path: $FINITEDEPTH_DATA/ref2.png
  coat_path: $FINITEDEPTH_DATA/coat2.png
  reference:
    templateROI: [200, 50, 1200, 200]
    substrateROI: [500, 250, 900, 600]
  substrate:
    type:
      name: CircSubst
      module: circsubstrate
    parameters:
      dp: 1.0
      minDist: 20.0
      param1: 100.0
      param2: 10.0
  coatinglayer:
    type:
      name: CircLayer
      module: circlayer
  analysis:
    parameters:
      subst_visual: output/subst.jpg
      subst_data: output/subst.csv
      layer_visual: output/layer.jpg
      layer_data: output/layer.csv
